### ISSUE TITLE
Context menu not loaded in non-Windows file explorer like DirectoryOpus

### ISSUE THREAD

**Issue by ccl13** [M2Team/NanaZip#73] opened 2021-12-11 04:17 UTC
When used in DirectoryOpus, the context menu item of NanoZip shows as only an item with no action. No submenu, no reaction when clicked. Suspect the same in other 3rd party file-explorer-like tools.

**Comment by SakuraNeko** [comment] 2021-12-11 04:28
@ccl13 :

This is a known issue, Please see #21. 

Sakura Neko

**Comment by SakuraNeko** [comment] 2021-12-11 04:29
Duplicate of #21

**Closed** 2021-12-11 04:29 UTC
Labels: bug
