### ISSUE TITLE
how to select compression level?

### ISSUE THREAD

**Issue by megapro17** [M2Team/NanaZip#234] opened 2022-11-03 20:21 UTC
i'm want to create 7z archive with zstd method. but there's no way to change compression level, when you do it resets codec to lzma2. and there's maximum value only 9, when zstd supports up to 22

**Comment by AndromedaMelody** [comment] 2023-03-11 11:50
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Modernizing UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.

**Closed by AndromedaMelody** 2023-03-11 11:50 UTC
Labels: suggestion, enhancement

**Comment by MouriNaruto** [comment] 2023-03-11 14:57
https://github.com/M2Team/NanaZip/commit/3f10b7def229968b4066ef8f405860a82fe86833

This commit should fix this issue. Please wait for the next NanaZip release. The issue is closed.

Kenji Mouri
