### ISSUE TITLE
Warnings on PowerShell sessions not related to NanaZip

### ISSUE THREAD

**Issue by Fabio286** [M2Team/NanaZip#117] opened 2022-02-14 15:29 UTC
Hi developers,

I was running some console applications, not related to NanaZip and I encountered this warning, several times.
My operating system is Windows 11 (beta 22000.526).

Feel free to ask if you need more details.

![image](https://user-images.githubusercontent.com/31471771/153891868-6bfb9cea-298e-4c90-aff7-e02206920fd5.png)

**Comment by MouriNaruto** [comment] 2022-02-16 13:53
@Fabio286 

I guess, this warning is caused by no verbs defined by file type associations in NanaZip's AppX manifest.

I have tried to make a fix. https://github.com/M2Team/NanaZip/commit/cd43232e239a81dc3153c6a6eb4e5235cbc84dad

But I hope you can provide me the script which you used to find the issue because I need to test NanaZip and confirm the fix result.

Kenji Mouri

**Comment by Fabio286** [comment] 2022-02-16 15:04
Hi Kenji,

sorry for missing reply, the issue occurs when I run some applications of my company that i can't  distribute outside.
I was trying to create a script to replicate same conditions. I hope to finish on next days.

**Comment by Fabio286** [comment] 2022-02-17 09:52
Here we are!
Following the repo with the script to reproduce this bug.
https://github.com/Fabio286/reproduce-nanazip.git

If you don't are familiar with Node.js, just install last LTS then inside the script folder run `npm i` and then `node .`

Let me know if something is wrong.

**Comment by MouriNaruto** [comment] 2022-02-24 14:57
@Fabio286 I had tested with you example and found the issue seems to be fixed.

Kenji Mouri

**Comment by Fabio286** [comment] 2022-02-24 15:00
@MouriNaruto 
Nice! I really appreciate this project ❤️

**Comment by MouriNaruto** [comment] 2022-03-07 07:19
This issue won't be closed until next version released.

Kenji Mouri

**Comment by MouriNaruto** [comment] 2022-03-18 15:35
This issue is fixed in NanaZip 1.1 Stable. So, I close this issue.

You can read the release note from https://github.com/M2Team/NanaZip/releases/tag/1.1.

Kenji Mouri

**Closed by MouriNaruto** 2022-03-18 15:35 UTC
Labels: bug
