### ISSUE TITLE
Unable to choose dictionary size with FLZMA2

### ISSUE THREAD

**Issue by crazybusta94** [M2Team/NanaZip#158] opened 2022-06-05 15:32 UTC
Hello,

Why can't I select dictionary size with FLZMA2 ?
It's possible with 7-zip ZS

![NanaZipG_y2WnxKkife](https://user-images.githubusercontent.com/48189352/172058185-88c1d09a-d935-43d5-992e-ac5ccd517253.png)

**Comment by octopushugger** [comment] 2022-07-02 12:19
This is part of a larger issue that compression level settings are missing from most of the methods. Zstandard should have 1-22, Brotli should have 0-11, etc. Whatever setting is used by default in NanaZip is also not listed.

**Comment by AndromedaMelody** [comment] 2023-03-11 11:44
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Modernizing UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.

**Closed by AndromedaMelody** 2023-03-11 11:44 UTC
Labels: bug, archived

**Comment by MouriNaruto** [comment] 2023-03-11 14:57
https://github.com/M2Team/NanaZip/commit/3f10b7def229968b4066ef8f405860a82fe86833

This commit should fix this issue. Please wait for the next NanaZip release. The issue is closed.

Kenji Mouri
