### ISSUE TITLE
Add to Archive - Brotli method bug

### ISSUE THREAD

**Issue by hl2guide** [M2Team/NanaZip#179] opened 2022-07-13 15:51 UTC
When compressing a folder using the "Add to archive" dialog and setting the compression method to Brotli, then trying to change the compression level incorrectly changes the method to LZMA2.

**Comment by hl2guide** [comment] 2022-07-13 18:00
Example GIF:
![example](https://user-images.githubusercontent.com/17044982/178800161-9c5c407a-c833-4150-845e-5fc7ed5ccbce.gif)

**Comment by AndromedaMelody** [comment] 2023-03-11 11:47
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Modernizing UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.

**Closed by AndromedaMelody** 2023-03-11 11:47 UTC
Labels: bug

**Comment by MouriNaruto** [comment] 2023-03-11 14:57
https://github.com/M2Team/NanaZip/commit/3f10b7def229968b4066ef8f405860a82fe86833

This commit should fix this issue. Please wait for the next NanaZip release. The issue is closed.

Kenji Mouri
